version: 2.1

jobs:
  # Building the project is going to start
  build:
    machine:
      image: ubuntu-2004 # Specify the free Linux image available in CircleCI
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Update npm packages
          command: npm update
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip  # Install Python 3 pip
            sudo pip3 install awscli --upgrade   # Install AWS CLI
      - run: cd ./app && npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  # Deploying the code to AWS S3 Bucket
  deploy: 
    machine:
      image: ubuntu-18.04 # You can keep the Ubuntu image for deployment
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: 
          name: Configuring AWS
          command: |
            ls
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync ./app/build s3://${AWS_S3_BUCKET}
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

