version: 2.1

jobs:
  # Building the project is going to start
  build:
    machine:
      image: ubuntu-2204:2024.01.1
    # If running ARM, the resource class needs to be added. Omitting this defaults to amd64
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Update npm package
          command: sudo apt-get install -y npm
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip  # Install Python 3 pip
            sudo pip3 install awscli --upgrade   # Install AWS CLI
      - run:
          name: Navigate to project directory
          command: | 
            cd CircleCI-ReactJS-project/app
            npm install
      - run:
          name: Build project
          command: npm run build
          environment:
            CI: true

  # Deploying the code to AWS S3 Bucket
  deploy: 
    machine:
      image: ubuntu-2204:2024.01.1 # You can keep the Ubuntu image for deployment
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: 
          name: Configuring AWS
          command: |
            ls
            if [ $CIRCLE_BRANCH = 'main' ]; then
              aws s3 sync ./app/build s3://${AWS_S3_BUCKET}
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

